### PR TITLE
feat: Support RISC-V RVV

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks @howjmay ! Do you know if it possible to run tests on RISC-V on github?

**Comment by howjmay** [comment]
Hi. I have a repo to host prebuilt binary of riscv-gnu-toolchain. 
RVV has been supported but intrinsics are not, so I need to use gcc 14 to build the gnu toolchain

https://github.com/howjmay/prebuilt-riscv-toolchain

**Comment by romange** [comment]
@howjmay  do you mind signing the commit?

**Comment by howjmay** [comment]
signed! Thanks

**Comment by romange** [comment]
@howjmay  it's not really signed - see the following github article: 
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
I used gpg to create a sign key and add it to my github account.

both helio and dragonfly require signed commits.

**Comment by howjmay** [comment]
done!

**Comment by romange** [comment]
Thanks!

**Comment by howjmay** [comment]
thank you too

**Pull request merged**
